print "Solangie Paola Garavito 624702"
print ""
print "****************************************************"
print "************* CALCULO SERIE FIBONACCI **************"
print "****************************************************"
